### ISSUE TITLE
Error when launching the bot.

### ISSUE THREAD

**Issue by N07070** [ahoskins/snapper#1]
I was trying to run the bot, but at first, I got this error :

```
[2015-04-08 19:25:27,766] Starting new HTTPS connection (1): feelinsonice-hrd.appspot.com
[2015-04-08 19:25:28,034] "POST /bq/login HTTP/1.1" 400 None
Traceback (most recent call last):
  File "opendatabot.py", line 53, in <module>
    bot = ReflectorBot(args.username, args.password)
  File "build/bdist.linux-x86_64/egg/lib/bot.py", line 19, in __init__
  File "build/bdist.linux-x86_64/egg/pysnap/__init__.py", line 100, in login

  File "build/bdist.linux-x86_64/egg/pysnap/__init__.py", line 83, in _request

  File "build/bdist.linux-x86_64/egg/pysnap/utils.py", line 88, in request
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request
```

**Comment by mavieth** [comment]
I had a similar issue launching the bot. It said it was an old version of snapchat.

**Comment by N07070** [comment]
Then, we need to get rid of pysnap, and build our own with blackjack and
hookers ?

**Comment by mavieth** [comment]
Exactly my thoughts.

**Comment by N07070** [comment]
When and how do we start ?

**Comment by ahoskins** [comment]
Hmmm, that's a shame.  I know there was some drama a while ago with Snapchat blocking unofficial apps from using their API.  So this is likely the same sort of situation - which is too bad.

I don't know of any solutions.
