### ISSUE TITLE
Error on Launch

### ISSUE THREAD

**Issue by mavieth** [ahoskins/snapper#2]
[2015-04-08 17:28:05,234] Starting new HTTPS connection (1): feelinsonice-hrd.appspot.com
[2015-04-08 17:28:06,509] "POST /loq/login HTTP/1.1" 200 None
Traceback (most recent call last):
  File "first.py", line 31, in <module>
    bot = MikulBot("","")
  File "/usr/local/lib/python2.7/dist-packages/snapchat_bots-0.1-py2.7.egg/lib/bot.py", line 19, in **init**
    self.client.login(username, password)
  File "/usr/local/lib/python2.7/dist-packages/pysnap-0.1.1-py2.7.egg/pysnap/**init**.py", line 113, in login
    raise Exception(result.get('message', 'unknown error'))
Exception: Oops! You are using an older version of Snapchat. Please update to the latest version to log in :)

**Comment by ahoskins** [comment]
See #1
